const reelsData=[
    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },

    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },
    {name:"Alexender Walker",
    type:"Engineering Student",
    time:"24 mins ago",
    postText:`🚀 Exciting News! 🚀
    I have officially completed my third year as an engineering student, and what an incredible journey it has been! 🎓🔧`,
    typeImg:require('../assets/images/security-user.png'),
    postImage:require('../assets/images/security-user.png'),
    likeImage:require('../assets/images/heart.png'),
    commentImage:require('../assets/images/image_message.png'),
    ShareImage:require('../assets/images/send-2.png'),
    SaveImage:require('../assets/images/image_archive-tick.png'),
    },


]

export default reelsData